### ISSUE TITLE
errors while scraping syslog-ng 

### ISSUE THREAD

**Issue by saibug** [brandond/syslog_ng_exporter#7]
Hi , 

I'm trying to scrape syslog-ng metrics using prometheus exporter through docker. I'm facing this issue : 

![image](https://user-images.githubusercontent.com/32570331/219426652-dbf80b6e-f1dd-45c1-8733-80ee54082951.png)

![image](https://user-images.githubusercontent.com/32570331/219428182-8fc49a7a-1533-43b2-b753-b89699a1cd03.png)

Could you help please ? 

Thanks

**Comment by saibug** [comment]
@brandond  any help please ? 

thank you in advance

**Comment by brandond** [comment]
Did you mount the syslog-ng.ctl socket into the container at the appropriate path?

**Comment by saibug** [comment]
Yes the fs is binded
Very strange!!

**Comment by brandond** [comment]
Hmm. Is there anything interesting in the syslog-ng logs? Not exactly sure what connection refused means on a unix socket.

**Comment by saibug** [comment]
syslog-ng logs really doesn't help .. i have only restart/ reload messages :(

**Comment by saibug** [comment]
syslog-ng versin : 
```
syslog-ng 3 (3.33.2)
```

**Comment by brandond** [comment]
Can you show how you've mounted the socket into the container? I suspect that the path just isn't right and you're not actually connecting to syslog-ng at all.

**Comment by saibug** [comment]
ok, see below screens

how i run docker container 

![image](https://user-images.githubusercontent.com/32570331/220465290-0a76c272-941b-4a19-92d8-71734e776ca6.png)

**Comment by brandond** [comment]
You appear to be mounting the binary at /usr/sbin/syslog-ng-ctl into the container, instead of the actual syslog-ng control socket. The cli tool binary is not the control socket. Find the syslog-ng control socket and mount that in. Most distros place the socket at `/var/lib/syslog-ng/syslog-ng.ctl`, which is the default used by this tool.

This is actually covered in the example in the readme, I'm curious why you are trying to mount the binary in instead?
https://github.com/brandond/syslog_ng_exporter/blob/master/README.md#using-docker

**Comment by saibug** [comment]
you're right 
now exporter works fine :) 

![image](https://user-images.githubusercontent.com/32570331/220472060-3bd4671b-7f61-4a47-ae9d-76f63a5c86ac.png)

@brandond  thank you for your helps :)
